name: Pint Code Style

on:
  push:
    paths:
      - '**.php'
  pull_request:
    branches:
      - main
    paths:
      - '**.php'
  workflow_dispatch:

jobs:
  php-cs-fixer:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          ref: ${{ github.head_ref }}

      - name: Run Pint Code Style Fixer
        uses: aglipanci/laravel-pint-action@0.1.0

      - name: Commit changes
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Fix styling
